---
title: "writeup2.Rmd"
output: html_document
---
##The Context of Rising Global Temperatures

Using global temperature data from NASA's Goddard Institute for Space Studies (<http://data.giss.nasa.gov/gistemp/), we wanted to investigate whether and how changes in global temperature over many decades affected changes in flood incidence. In the first plot, an average temperature baseline was drawn based on the years 1951 to 1980; clearly, the trend has been an inexorable march up, but it is telling that since shortly before 1980, the global annual temperature mean has never returned to that average. 

**What to say about the 1985 line? Also is the degrees scale correct?**

In the second set of plots, we compare annual mean temperature flucutations over the last 130 years in the northern and southern hemispheres. Rather intuitively,  heavier energy use, greater overall population, and greater number of cities and other dense population clusters in the northern hemisphere have accelerated the annual mean temperature increase far more significantly than in the southern hemisphere. In particular, these factors' effects did not come lead to the temperature explosion in the northern hemisphere until the mid-20th century, when energy consumption really boomed.

##Frequency and Magnitude of Floods Worldwide

Here we take an initially broad view of the incidence of severe global floods since 1985 and then narrow our scope to focus on individual countries. In the first plot, over thirty years, we observe that the number of floods worldwide has been increasing overall and at roughly the same rate between those under and over magnitude of 6. It can also be seen that the number of floods changes sinusoidally, following the roughly decade-long global weather phenomena El Nino and La Nina. 

As expected, if we then break down flood incidence by country, we see that of the twelve countries with the most floods, the number of floods has risen in more cases than not. We could not find any geographical correlation with flood incidence decrease or increase. 

##Text Analysis

We analyzed the news headlines accompanying the NOAA flood data and found that there were certain words and ideas that resonated across most countries and magnitude groupings, as well as differed. All word clouds we generated contained as the most commonly occurring words the following: "people", "river", "water", and "river". But for floods of magnitude less than 6, emphasis was rather evenly spread amongst "rain", "river", "heavy", and "people", while for floods greater than magnitude 6, emphasis shifted singularly to "people". 

Cultural differences may also come into play in the differences between the word clouds for China, India, and the US. China and India's headlines more frequently mentioned "people" and, quite uniquely, "provinces" and "villages", respectively. Meanwhile, headlines in the US mentioned more often the cause of the flood itself (ie. "river", "water", "rain") rather than the people and communities affected. Interestingly, the most commonly used word for communities in the US was "county". 